runtime: python312
env: standard
instance_class: F1

entrypoint: gunicorn -b :$PORT config.wsgi

handlers:
  - url: /static
    static_dir: staticfiles

  - url: /.*
    script: auto

env_variables:
  DB_HOST: "34.142.192.182"
  DB_NAME: "uni_db"
  DB_USER: "pt_user"
  DB_PASS: "123123123"