runtime: python312
env: standard
instance_class: F1

entrypoint: gunicorn -b :$PORT config.wsgi

handlers:
  - url: /static
    static_dir: staticfiles

  - url: /.*
    script: auto

env_variables:
  DB_HOST=103.3.173.137
  DB_NAME=db30
  DB_USER=root
  DB_PWD=returntoRL!
  DB_PORT=3306

  SOCIAL_AUTH_GITHUB_KEY=Ov23liadupAuJUoHvtg0
  SOCIAL_AUTH_GITHUB_SECRET=4157da5a852e5dcb49dc9316eafe64331c3b58f4

  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=178830027421-o5ac3m89hinnvgt6aj2al1hngqlie8td.apps.googleusercontent.com"
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=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