# Generated by Django 6.0.3 on 2026-03-21 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50)])),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='orm.trainer')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(100)])),
                ('instructions', models.TextField()),
                ('def_sets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('def_reps', models.IntegerField(default=0)),
                ('def_weight', models.IntegerField(default=0, help_text='in Kgs')),
                ('def_duration', models.IntegerField(default=0, help_text='in Minutes')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='orm.trainer')),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('goals', models.CharField(max_length=150)),
                ('preferred_times', models.CharField(max_length=150)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='orm.trainer')),
            ],
            options={
                'db_table': 'clients',
                'unique_together': {('trainer', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('trainer_review', models.TextField(blank=True, null=True)),
                ('client_remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='orm.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='orm.trainer')),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('pre_sets', models.PositiveIntegerField(default=0)),
                ('pre_reps', models.PositiveIntegerField(default=0)),
                ('pre_weight', models.PositiveIntegerField(default=0)),
                ('pre_duration', models.DurationField(blank=True, null=True)),
                ('actual_sets', models.PositiveIntegerField(blank=True, default=0)),
                ('actual_reps', models.PositiveIntegerField(blank=True, default=0)),
                ('actual_weight', models.PositiveIntegerField(blank=True, default=0)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='orm.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='orm.workout')),
            ],
            options={
                'db_table': 'workout_exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='orm.exercise')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_links', to='orm.tag')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_tags', to='orm.trainer')),
            ],
            options={
                'db_table': 'exercise_tags',
                'unique_together': {('exercise', 'tag')},
            },
        ),
    ]
