# Generated by Django 6.0.3 on 2026-03-18 06:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(50)])),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='orm.trainer')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(100)])),
                ('instructions', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(100)])),
                ('def_sets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('def_reps', models.IntegerField(default=0)),
                ('def_weight', models.IntegerField(default=0, help_text='in Kgs')),
                ('def_duration', models.IntegerField(default=0, help_text='in Minutes')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='orm.trainer')),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='orm.exercise')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exercise_links', to='orm.tag')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_tags', to='orm.trainer')),
            ],
            options={
                'db_table': 'exercise_tags',
                'unique_together': {('exercise', 'tag')},
            },
        ),
    ]
