# Generated by Django 6.0.3 on 2026-03-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_workoutexercise_actual_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_duration',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_reps',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_sets',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_weight',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='pre_duration',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='pre_reps',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='pre_sets',
            field=models.PositiveIntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='pre_weight',
            field=models.PositiveIntegerField(db_default=0),
        ),
    ]
