# Generated by Django 6.0.3 on 2026-04-01 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_date',
            new_name='scheduled_date',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('scheduled_date', 'scheduled_time')},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(80)]),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
    ]
