# Generated by Django 6.0.3 on 2026-03-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_alter_workoutexercise_actual_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='is_done',
            field=models.BooleanField(db_default=False),
        ),
    ]
